export const CARTADD_DATA = "CARTADD_DATA"
export const GET_TO_CART = "GET_TO_CART"
export const DELETE_CART_PRODUCT = "DELETE_CART_PRODUCT"

export const CART_INCREMENTCOUNTER = "CART_INCREMENTCOUNTER"
export const CART_DECREMENTCOUNTER = "CART_DECREMENTCOUNTER"

export const SIGNUP_USER = "SIGNUP_USER"
export const EMAIL_VERIFY = "EMAIL_VERIFY"

// alert
export const SET_ALERT = "SET_ALERT"
export const RESET_ALERT = "RESET_ALERT"

// Login
export const LOGIN_USER = "LOGIN_USER"
export const LOGGED_USER = "LOGGED_USER"

// LogoutUser
export const LOGOUT_USER = "LOGOUT_USER"
export const LOGGEDINOUT_USER = "LOGGEDINOUT_USER"

// googlelogin
export const GOOGLELOGIN_USER = "GOOGLELOGIN_USER"
export const FACEBOOK_LOGIN = "FACEBOOK_LOGIN"

export const FORGET_PASSWORD_USER = "FORGET_PASSWORD_USER"


// category

export const ERROR_CATOGORIES = "ERROR_CATOGORIES"

export const GET_CATOGORIES = "GET_CATOGORIES"
export const ADD_CATOGORIES = "ADD_CATOGORIES"

export const UPDATE_CATOGORIES = "UPDATE_CATOGORIES"
export const DELETE_CATOGORIES = "DELETE_CATOGORIES"

// product

export const ERROR_PRODUCT = "ERROR_PRODUCT"

export const GET_PRODUCT = "GET_PRODUCT"
export const ADD_PRODUCT = "ADD_PRODUCT"

export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"

// cartproduct

export const CART_PRODUCT_ERROR = "CART_PRODUCT_ERROR"

export const CARTGET_PRODUCT = "CARTGET_PRODUCT"
export const CARTADD_PRODUCT = "CARTADD_PRODUCT"

export const ADD_ORDER = "ADD_ORDER"
export const GET_ORDER = "GET_ORDER"
export const ERROR_ORDER = "ERROR_ORDER"